### PR TITLE
Alignment with Hornet 1.0.5

### PR DESCRIPTION
**Pull request by jmcanterafonseca-iota**
# Description of change

Alignment with Hornet 1.0.5

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Manual testing

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by peterokwara — APPROVED** [review]
Everything is working well. That is :
- Running a node and adding a peer manually
- Running a node which has been set up for autopeering

**Comment by peterokwara** [comment]
I had to add the configurations for autopeering. Maybe as an enhancement we could have the script be able to set up either autopeering or manual peering.

**Comment by jmcanterafonseca-iota** [comment]
> I had to add the configurations for autopeering. Maybe as an enhancement we could have the script be able to set up either autopeering or manual peering.

Yes, that's an enhancement. Could you open an issue @peterokwara ? in the meantime I am merging this one

**Comment by peterokwara** [comment]
Sure, I can do that asap

**Pull request merged**
